'use strict';

const MAX_BYTES = 20 * 1024 * 1024;
const MAX_PIXELS = 32_000_000;
const allowed = new Map([['image/jpeg', [0xff, 0xd8, 0xff]], ['image/png', [0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]], ['image/webp', [0x52,0x49,0x46,0x46]]]);
const $ = id => document.getElementById(id);
const els = {file:$('file'),clear:$('clear'),status:$('status'),canvas:$('preview'),stage:$('stage'),crop:$('crop'),empty:$('empty'),zoom:$('zoom'),rotation:$('rotation'),margin:$('margin'),reset:$('reset'),format:$('format'),quality:$('quality'),language:$('language')};
const ctx = els.canvas.getContext('2d', {alpha:false});
let image = null, objectUrl = null, lang = 'ru';
let crop = {x:.2,y:.15,w:.6,h:.7};
let drag = null;

const messages = {
 ru:{brand:'Локальная подготовка фото',privacyTitle:'Ваше фото остаётся на устройстве.',privacy:'Приложение не загружает, не хранит, не анализирует и не ищет изображения. Обработка выполняется только в памяти браузера. Для внешнего поиска сначала экспортируйте файл, затем загрузите его вручную на выбранном сайте.',heading:'Подготовить изображение локально',limits:'JPEG, PNG или WebP · до 20 МБ · до 32 мегапикселей',choose:'Выбрать фото',clear:'Удалить текущее фото',ready:'Фото не выбрано.',editor:'Ручное кадрирование',empty:'Выберите фото, чтобы начать.',keyboard:'Перетаскивайте рамку и углы. Клавиши-стрелки перемещают рамку; Shift + стрелки меняют её размер.',zoom:'Масштаб',rotation:'Поворот',margin:'Отступ квадратного кадра',reset:'Сбросить правки',exportTitle:'Чистый экспорт',format:'Формат',quality:'Качество JPEG',clean:'Полное чистое перекодирование',portrait:'Портрет 4:5',square:'Квадратный кадр лица',exportNote:'Canvas-перекодирование предназначено для удаления обычных метаданных изображения, но не гарантирует стирание всех возможных следов.',external:'Внешние сервисы',manual:'Экспортируйте изображение и загрузите его вручную. Ссылки не содержат данных вашего фото.',manualLabel:'загрузить вручную',footer:'Работает без сервера. Не используйте внешние сервисы для чувствительных изображений.',loaded:'Фото готово к редактированию.',bad:'Файл не является корректным JPEG, PNG или WebP.',large:'Файл превышает 20 МБ.',pixels:'Изображение превышает 32 мегапикселя.',exported:'Файл экспортирован; обычные метаданные не копируются.'},
 en:{brand:'Local photo preparation',privacyTitle:'Your photo stays on your device.',privacy:'This app does not upload, store, analyze, or search images. Processing occurs only in browser memory. To use external search, export the file and then upload it manually on the selected site.',heading:'Prepare an image locally',limits:'JPEG, PNG, or WebP · up to 20 MB · up to 32 megapixels',choose:'Choose photo',clear:'Clear current photo',ready:'No photo selected.',editor:'Manual crop',empty:'Choose a photo to begin.',keyboard:'Drag the frame and its corners. Arrow keys move it; Shift + arrows resize it.',zoom:'Zoom',rotation:'Rotation',margin:'Square crop margin',reset:'Reset edits',exportTitle:'Clean export',format:'Format',quality:'JPEG quality',clean:'Full clean re-encode',portrait:'4:5 portrait',square:'Square face crop',exportNote:'Canvas re-encoding is intended to remove ordinary image metadata, but cannot guarantee erasure of every possible trace.',external:'External services',manual:'Export the image and upload it manually. Links contain no data from your photo.',manualLabel:'upload manually',footer:'Runs without a server. Do not use external services for sensitive images.',loaded:'Photo is ready to edit.',bad:'The file is not a valid JPEG, PNG, or WebP.',large:'The file exceeds 20 MB.',pixels:'The image exceeds 32 megapixels.',exported:'File exported; ordinary metadata is not copied.'}
};
function t(key){return messages[lang][key]}
function status(key, error=false){els.status.textContent=t(key);els.status.style.color=error?'#ff8f8f':''}
function revoke(){if(objectUrl){URL.revokeObjectURL(objectUrl);objectUrl=null}}
function controls(on){[els.clear,els.zoom,els.rotation,els.margin,els.reset,...document.querySelectorAll('.export')].forEach(el=>el.disabled=!on)}
function clearImage(){revoke();image=null;els.file.value='';els.crop.hidden=true;els.empty.hidden=false;controls(false);ctx.clearRect(0,0,els.canvas.width,els.canvas.height);status('ready')}

async function signature(file){const b=new Uint8Array(await file.slice(0,16).arrayBuffer());if(file.type==='image/webp')return allowed.get(file.type).every((v,i)=>b[i]===v)&&String.fromCharCode(...b.slice(8,12))==='WEBP';const sig=allowed.get(file.type);return sig&&sig.every((v,i)=>b[i]===v)}
els.file.addEventListener('change', async()=>{const file=els.file.files[0];if(!file)return;if(file.size>MAX_BYTES){clearImage();status('large',true);return}if(!allowed.has(file.type)||!(await signature(file))){clearImage();status('bad',true);return}revoke();const url=URL.createObjectURL(file);const candidate=new Image();candidate.decoding='async';candidate.onload=()=>{if(!candidate.naturalWidth||!candidate.naturalHeight||candidate.naturalWidth*candidate.naturalHeight>MAX_PIXELS){URL.revokeObjectURL(url);clearImage();status('pixels',true);return}objectUrl=url;image=candidate;reset();controls(true);els.empty.hidden=true;els.crop.hidden=false;status('loaded')};candidate.onerror=()=>{URL.revokeObjectURL(url);clearImage();status('bad',true)};candidate.src=url});

function reset(){if(!image)return;els.zoom.value=100;els.rotation.value=0;els.margin.value=12;crop={x:.2,y:.15,w:.6,h:.7};draw();placeCrop();/* revoke/recreate to minimize stale URL lifetime */const old=objectUrl;if(old){URL.revokeObjectURL(old);objectUrl=null}}
function draw(){if(!image)return;const w=els.stage.clientWidth||800,h=els.stage.clientHeight||600,d=devicePixelRatio||1;els.canvas.width=Math.round(w*d);els.canvas.height=Math.round(h*d);ctx.setTransform(d,0,0,d,0,0);ctx.fillStyle='#080b10';ctx.fillRect(0,0,w,h);const angle=Number(els.rotation.value)*Math.PI/180,z=Number(els.zoom.value)/100;const iw=Math.abs(Math.cos(angle))*image.naturalWidth+Math.abs(Math.sin(angle))*image.naturalHeight,ih=Math.abs(Math.sin(angle))*image.naturalWidth+Math.abs(Math.cos(angle))*image.naturalHeight;const scale=Math.min(w/iw,h/ih)*z;ctx.save();ctx.translate(w/2,h/2);ctx.rotate(angle);ctx.drawImage(image,-image.naturalWidth*scale/2,-image.naturalHeight*scale/2,image.naturalWidth*scale,image.naturalHeight*scale);ctx.restore()}
function placeCrop(){const w=els.stage.clientWidth,h=els.stage.clientHeight;Object.assign(els.crop.style,{left:`${crop.x*w}px`,top:`${crop.y*h}px`,width:`${crop.w*w}px`,height:`${crop.h*h}px`})}
function clamp(){crop.w=Math.min(.96,Math.max(.08,crop.w));crop.h=Math.min(.96,Math.max(.08,crop.h));crop.x=Math.max(.02,Math.min(.98-crop.w,crop.x));crop.y=Math.max(.02,Math.min(.98-crop.h,crop.y));placeCrop()}
els.crop.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,start:{...crop},handle:e.target.dataset.handle||'move'};els.crop.setPointerCapture(e.pointerId);e.preventDefault()});
els.crop.addEventListener('pointermove',e=>{if(!drag)return;const dx=(e.clientX-drag.x)/els.stage.clientWidth,dy=(e.clientY-drag.y)/els.stage.clientHeight,{start:s,handle:h}=drag;crop={...s};if(h==='move'){crop.x+=dx;crop.y+=dy}else{if(h.includes('w')){crop.x+=dx;crop.w-=dx}else crop.w+=dx;if(h.includes('n')){crop.y+=dy;crop.h-=dy}else crop.h+=dy}clamp()});
els.crop.addEventListener('pointerup',()=>drag=null);
els.crop.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;const n=e.altKey?.001:.01,dx=e.key==='ArrowLeft'?-n:e.key==='ArrowRight'?n:0,dy=e.key==='ArrowUp'?-n:e.key==='ArrowDown'?n:0;if(e.shiftKey){crop.w+=dx;crop.h+=dy}else{crop.x+=dx;crop.y+=dy}clamp();e.preventDefault()});
[els.zoom,els.rotation].forEach(el=>el.addEventListener('input',draw));els.reset.addEventListener('click',reset);els.clear.addEventListener('click',clearImage);addEventListener('resize',()=>{draw();placeCrop()});

function renderExport(kind){const mime=els.format.value,quality=Number(els.quality.value)/100;let source=els.canvas,sx=0,sy=0,sw=source.width,sh=source.height;if(kind==='clean'){source=image;sw=image.naturalWidth;sh=image.naturalHeight}else{sx=crop.x*sw;sy=crop.y*sh;sw=crop.w*sw;sh=crop.h*sh;const ratio=kind==='portrait'?4/5:1;const margin=kind==='square'?Number(els.margin.value)/100:0;sx-=sw*margin;sy-=sh*margin;sw*=1+2*margin;sh*=1+2*margin;if(sw/sh>ratio){const nw=sh*ratio;sx+=(sw-nw)/2;sw=nw}else{const nh=sw/ratio;sy+=(sh-nh)/2;sh=nh}sx=Math.max(0,sx);sy=Math.max(0,sy);sw=Math.min(sw,source.width-sx);sh=Math.min(sh,source.height-sy)}const max=kind==='clean'?Infinity:2400,out=document.createElement('canvas'),scale=Math.min(1,max/Math.max(sw,sh));out.width=Math.max(1,Math.round(sw*scale));out.height=kind==='portrait'?Math.max(5,Math.round(out.width/4)*5):kind==='square'?out.width:Math.max(1,Math.round(sh*scale));if(kind==='portrait')out.width=out.height/5*4;const o=out.getContext('2d',{alpha:mime==='image/png'});if(mime==='image/jpeg'){o.fillStyle='#fff';o.fillRect(0,0,out.width,out.height)}o.drawImage(source,sx,sy,sw,sh,0,0,out.width,out.height);out.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a'),names={clean:'photo-clean-reencode',portrait:'photo-portrait-4x5',square:'photo-square'};a.href=url;a.download=`${names[kind]}.${mime==='image/png'?'png':'jpg'}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),0);status('exported')},mime,quality)}
document.querySelectorAll('.export').forEach(b=>b.addEventListener('click',()=>renderExport(b.dataset.kind)));
els.language.addEventListener('click',()=>{lang=lang==='ru'?'en':'ru';document.documentElement.lang=lang;els.language.textContent=lang==='ru'?'EN':'RU';document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));status(image?'loaded':'ready')});
addEventListener('beforeunload',revoke);clearImage();
